name: Block Merge Based on Labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened]

jobs:
  label-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check labels
        uses: actions/github-script@v7
        with:
          script: |
            const disallowed = ['✅next release', 'do not merge ✋'];
            const labels = context.payload.pull_request.labels.map(l => l.name);
            const bad = labels.filter(l => disallowed.includes(l));
            if (bad.length > 0) {
              core.setFailed(`Cannot merge PR with labels: ${bad.join(', ')}`);
            } else {
              console.log("All clear to merge");
            }
